/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Wed Aug 31 01:24:49 CST 2016
 */
package org.apache.camel.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;
import org.codehaus.jackson.annotate.JsonProperty;

/**
 * Salesforce DTO for SObject WorkFeedbackTemplate
 */
@XStreamAlias("WorkFeedbackTemplate")
public class WorkFeedbackTemplate extends AbstractSObjectBase {

    // QuestionSetId
    private String QuestionSetId;

    @JsonProperty("QuestionSetId")
    public String getQuestionSetId() {
        return this.QuestionSetId;
    }

    @JsonProperty("QuestionSetId")
    public void setQuestionSetId(String QuestionSetId) {
        this.QuestionSetId = QuestionSetId;
    }

}
